export { default as axiosClient } from "./axiosClient";
export { default as authApi } from "./authApi";
export { default as userApi } from "./userApi";
export { default as aiApi } from "./aiApi";
export { default as debateApi } from "./debateApi";
export { default as topicApi } from "./topicApi";
export { default as eventApi } from "./eventApi";
export { default as competitionApi } from "./competitionApi";
export { default as paymentApi } from "./paymentApi";
